### ISSUE TITLE
missing dependencies on the install instructions

### ISSUE THREAD

**Issue by johnvblazic** [kentonl/neuralccg#2]
Hi,

I've been attempting to get the project installed and set up over the last few days and noticed that you're missing a few things from your dependencies list and you have at least one issue with the listed dependencies.

I have yet to get the full project working, but here's what I have so far.

Missing:
Protobuf - The version of the protoc-compiler you can get from apt-get is incompatible with the latest version of Bazel and will not recognize the protobuf files properly. The fix is to get the latest version of this compiler, link and instructions are here: https://github.com/google/protobuf/blob/master/src/README.md 

Incorrect:
Bazel - theBazel install instructions you have listed under dependencies does not install correctly for Ubuntu 16.04 for some reason. You can correct this by installing Bazel with apt-get (https://bazel.build/versions/master/docs/install-ubuntu.html)

I'll update with other pieces as I find them, and will hopefully get this working by the end of the day.

The good news is the maven project in the neuralccg directory packages just fine.

John

**Comment by johnvblazic** [comment]
I'm having trouble getting the setup.sh to get past the protobuf errors. See below for error message

~/Projects/neuralccg$ ./setup.sh 
Using cached data from neuralccg/data
Using cached binaries from neuralccg/lib
ERROR: /home/johnblazic/.cache/bazel/_bazel_johnblazic/f8f60f3a84c1b2faec5b5f0e37e9efc5/external/protobuf/protobuf.bzl:96:19: name 'HOST_CFG' is not defined.
ERROR: error loading package 'neuralccg': Extension 'protobuf.bzl' has errors.
INFO: Elapsed time: 0.070s
cp: cannot stat 'bazel-bin/neuralccg/libdecoder.so': No such file or directory
cp: cannot stat 'bazel-bin/neuralccg/libdecoder.so': No such file or directory

**Comment by kentonl** [comment]
Hi John,

Thanks for pointing out all of the issues. It looks newer versions of bazel was causing some problems. 

I've fixed these issues in 1f05312b207700fe6103577aae2359858d3a12c9 and updated the protobuf and bazel instructions as you've suggested.

Let me know if there are lingering problems.

Kenton

**Comment by johnvblazic** [comment]
Kenton,

The issue still isn't resolved, I haven't been able to complete the setup. The error in my second comment is still ongoing, I've been trying a number of different things and will continue pursuing them. I'll update if I find a fix, but can you let me know if you have any ideas?

**Comment by kentonl** [comment]
With the updated protobuf version, protobuf.bzl should not longer reference HOST_CFG. Perhaps it's still using an old version from the cache?

If deleting the cache and rebuilding does not work, could you paste the content of /home/johnblazic/.cache/bazel/_bazel_johnblazic/f8f60f3a84c1b2faec5b5f0e37e9efc5/external/protobuf/protobuf.bzl here?

**Comment by johnvblazic** [comment]
I wiped the directory and started over, rerunning setup.sh now. will update

**Comment by johnvblazic** [comment]
Well I'm at least onto a new error now.

~/Projects/neuralccg$ ./setup.sh 
Downloading data from lil.cs.washington.edu/resources
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  211M  100  211M    0     0  2309k      0  0:01:33  0:01:33 --:--:-- 1709k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 68.7M  100 68.7M    0     0  2450k      0  0:00:28  0:00:28 --:--:-- 1824k
model_tritrain_finetune_long/
model_tritrain_finetune_long/posTagger
model_tritrain_finetune_long/taggerflow/
model_tritrain_finetune_long/taggerflow/prefix_1.txt
model_tritrain_finetune_long/taggerflow/suffix_2.txt
model_tritrain_finetune_long/taggerflow/words.txt
model_tritrain_finetune_long/taggerflow/suffix_3.txt
model_tritrain_finetune_long/taggerflow/suffix_1.txt
model_tritrain_finetune_long/taggerflow/prefix_2.txt
model_tritrain_finetune_long/taggerflow/prefix_3.txt
model_tritrain_finetune_long/taggerflow/suffix_4.txt
model_tritrain_finetune_long/taggerflow/graph.pb
model_tritrain_finetune_long/taggerflow/prefix_4.txt
model_tritrain_finetune_long/unaryRules
model_tritrain_finetune_long/markedup
model_tritrain_finetune_long/params
model_tritrain_finetune_long/word_dict
model_tritrain_finetune_long/unaryRules_backup
model_tritrain_finetune_long/feature_dicts
model_tritrain_finetune_long/tagdict2
model_tritrain_finetune_long/seenRules
model_tritrain_finetune_long/unaryRules_deps
model_tritrain_finetune_long/categories
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 61.1M  100 61.1M    0     0  1561k      0  0:00:40  0:00:40 --:--:-- 1083k
Downloading binaries from lil.cs.washington.edu/resources
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 45.9M  100 45.9M    0     0  1601k      0  0:00:29  0:00:29 --:--:-- 2216k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 44.3M  100 44.3M    0     0  1450k      0  0:00:31  0:00:31 --:--:-- 1762k
.
INFO: Found 1 target...
INFO: From Compiling external/cnn/cnn/mp.cc:
external/cnn/cnn/mp.cc: In function 'std::vector<cnn::mp::Workload> cnn::mp::CreateWorkloads(unsigned int)':
external/cnn/cnn/mp.cc:65:11: warning: variable 'err' set but not used [-Wunused-but-set-variable]
       int err;
           ^
INFO: From Compiling external/cnn/cnn/nodes.cc:
external/cnn/cnn/nodes.cc: In member function 'virtual void cnn::SparsemaxLoss::forward_impl(const std::vector<const cnn::Tensor*>&, cnn::Tensor&) const':
external/cnn/cnn/nodes.cc:64:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (k = 0; k < rows; ++k) {
                   ^
external/cnn/cnn/nodes.cc:80:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (unsigned i = 0; i < rows; ++i) {
                            ^
ERROR: /home/johnblazic/Projects/neuralccg/neuralccg/BUILD:13:1: Linking of rule '//neuralccg:libdecoder.so' failed: Process exited with status 1 [sandboxed].
/usr/bin/ld.gold: error: cannot find -lboost_serialization
/usr/bin/ld.gold: error: cannot find -lboost_system
/usr/bin/ld.gold: error: cannot find -lboost_filesystem
collect2: error: ld returned 1 exit status
Use --strategy=CppLink=standalone to disable sandboxing for the failing actions.
Target //neuralccg:libdecoder.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 96.426s, Critical Path: 56.49s
cp: cannot stat 'bazel-bin/neuralccg/libdecoder.so': No such file or directory
cp: cannot stat 'bazel-bin/neuralccg/libdecoder.so': No such file or directory

**Comment by johnvblazic** [comment]
As an update to my first post, I think only the newest Bazel version needs to be installed, not the protobuf version as the setup process is pulling down a correct version of protobuf that is building now. I'm seeing bazel-<thing> directories even after the setup is failing with the error immediately above this. The project seems to be using the local protobuf rather than the system-wide installation.

Also, a ran a "bazel clean --expunge" command to fully clear the bazel cache, which i think helped. I had run the "bazel clean" since i installed the newer version, but i don't think it had completely cleared that cache

**Comment by kentonl** [comment]
Unfortunately, CNN (now DyNet) has boost as one of its dependencies. I'm not using it, since its serialization function is prone to silent failures. However, you'll still need to install some version of it for the code to run properly. The latest version has updated instructions.

Re protobuf: thanks for the clarification. I've removed that from the instructions.

**Comment by johnvblazic** [comment]
Ugh, I've worked with Boost before and am familiar with some of its peculiarities. Can you recommend a specific Boost version? I've used other libraries that break on version X+1 but work on X and X+2

**Comment by kentonl** [comment]
The boost version shouldn't matter, as long as the linker can find it. It's not actually used anywhere in this codebase. There are probably slimmer workarounds, but `sudo apt-get install libboost-all-dev` should do the trick.

**Comment by johnvblazic** [comment]
Nevermind, installing boost from apt-get fixed it.

From the DyNet instructions: "sudo apt-get install libboost-all-dev cmake mercurial"

Using cached data from neuralccg/data
Using cached binaries from neuralccg/lib
INFO: Found 1 target...
Target //neuralccg:libdecoder.so up-to-date:
  bazel-bin/neuralccg/libdecoder.so
INFO: Elapsed time: 0.354s, Critical Path: 0.21s

**Comment by johnvblazic** [comment]
So it looks like final install updates are:

Get newest Bazel (which you've already mentioned)
Get Boost (apt-get version works)

**Comment by johnvblazic** [comment]
As a follow-up question on the code itself, I'm working on a small project to see what kind of effect different word embeddings have on your system. I see the initial values in neuralccg/data/wordembeddings.raw, is there anything hard coded to the 50-dimension word embeddings you chose to use for this? IF you don't know off hand, that's fine, ill keep digging and trying stuff, just thought I'd ask to save myself a few hours if possible.

Thanks for the help on the install as well

John

**Comment by kentonl** [comment]
To use word embeddings with different dimensions, you just need to modify https://github.com/uwnlp/neuralccg/blob/master/neuralccg/experiments/train.conf#L52 and point to a different file here: https://github.com/uwnlp/neuralccg/blob/master/neuralccg/experiments/train.conf#L30. The rest of the model will adjust accordingly.

I'm closing this issue, unless there are other problems with the installation.
